export const areaData = [
  {
    areaCode: "INT",
    areaName: "International",
    orgCode: "ASM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    areaCode: "KLM",
    areaName: "Kalimantan",
    orgCode: "ASM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    areaCode: "JKT",
    areaName: "Jakarta",
    orgCode: "ASM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    areaCode: "MDN",
    areaName: "Medan",
    orgCode: "ASM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    areaCode: "SBY",
    areaName: "Surabaya",
    orgCode: "ASM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    areaCode: "BTM",
    areaName: "Batam",
    orgCode: "ASM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    areaCode: "PLN",
    areaName: "PLN",
    orgCode: "ASM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    areaCode: "MKS",
    areaName: "MAKASAR",
    orgCode: "ASM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    areaCode: "SUL",
    areaName: "Sulawesi",
    orgCode: "ASM",
    createdBy: "system",
    updatedBy: "system",
  },
];
