export const supplierData = [
  {
    warehouseCode: "OPS",
    name: "OUTPORT SUPPLY",
    orgCode: "ASM",
    areaCode: "INT",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "TRK",
    name: "TARAKAN",
    orgCode: "ASM",
    areaCode: "KLM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "BPP",
    name: "BALIKPAPAN",
    orgCode: "ASM",
    areaCode: "KLM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "DMG",
    name: "DAAN MOGOT",
    orgCode: "ASM",
    areaCode: "JKT",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "KDY",
    name: "KEDOYA",
    orgCode: "ASM",
    areaCode: "JKT",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "MDN",
    name: "MEDAN",
    orgCode: "ASM",
    areaCode: "MDN",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "SBY",
    name: "SURABAYA",
    orgCode: "ASM",
    areaCode: "SBY",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "PRD",
    name: "PARADE",
    orgCode: "ASM",
    areaCode: "JKT",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "BTM",
    name: "BATAM",
    orgCode: "ASM",
    areaCode: "BTM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "PRD",
    name: "BANJARMASIN",
    orgCode: "ASM",
    areaCode: "KLM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "KBR",
    name: "KALBAR",
    orgCode: "ASM",
    areaCode: "KLM",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "PLN",
    name: "PLN",
    orgCode: "ASM",
    areaCode: "PLN",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "MKS",
    name: "MAKASAR",
    orgCode: "ASM",
    areaCode: "MKS",
    createdBy: "system",
    updatedBy: "system",
  },
  {
    warehouseCode: "KNW",
    name: "KONAWE",
    orgCode: "ASM",
    areaCode: "SUL",
    createdBy: "system",
    updatedBy: "system",
  },
];
